# Site settings
title: YAB
email: 3h4x.github.io@gmail.com
description: >
  yet another blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://3h4x.github.io" # the base hostname & protocol for your site
github_username: 3h4x

# Build settings
markdown: kramdown

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

excerpt_separator: <!-- readmore -->

plugins:
  - jekyll-sitemap
