# Site settings
title: YAB Marcin Brański
email: mbr@touk.pl
description: >
  YAB - yet another blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://3h4x.github.io" # the base hostname & protocol for your site
twitter_username: 3h4xx
github_username: 3h4x

# Build settings
markdown: kramdown

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

gems:
  - jekyll-sitemap
