# Site settings
title: 3h4x.github.io
email: 3h4x.github.io@gmail.com
description: >
  YAB - yet another blog on the internet!
  Container orchestration, observability tools, continuous intergration/delivery/deployment, terraform infrastructure
  as code, cloud like AWS/GCP and any other technology I use.
baseurl: ""
url: "https://3h4x.github.io"
github_username: 3h4x

author:
  name: 3h4x
  email: "3h4x.github.io@gmail.com"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

highlighter: rouge

pages_list:
  Archive: '/archive'
  Tags: '/tags'

google_analytics: 'UA-58462461-1'

theme: minima
show_excerpts: true

excerpt_separator: <!-- readmore -->

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
  - jekyll-tagging-related_posts

minima:
  social_links:
    github: 3h4x
    rss: rss

  disqus:
    shortname: 3h4xgithubio
